version: '3.8'

services:
  web:
    build: .
    command: flask run --host=0.0.0.0 --debug
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: src/app:create_app
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:Nueva123@db:5432/flask_psychology
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Nueva123
      POSTGRES_DB: flask_psychology

volumes:
  postgres_data: