"""session

Revision ID: 33ac841cc0b8
Revises: 8cca9293fe82
Create Date: 2024-10-06 02:32:58.048973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '33ac841cc0b8'
down_revision = '8cca9293fe82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('assist', sa.String(length=3), nullable=False))
        batch_op.add_column(sa.Column('pay', sa.String(length=3), nullable=True))
        batch_op.drop_column('created')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('pay')
        batch_op.drop_column('assist')
        batch_op.drop_column('session_date')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
