"""modify

Revision ID: 88df872d22a2
Revises: b3a31cafc702
Create Date: 2024-10-15 02:31:39.342028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88df872d22a2'
down_revision = 'b3a31cafc702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurrence_end', sa.Date(), nullable=True))
        batch_op.alter_column('recurrence_interval',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('recurrence_interval',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('recurrence_end')

    # ### end Alembic commands ###
