"""increase value

Revision ID: 8b300e44c76d
Revises: 8d0746779509
Create Date: 2024-11-03 23:55:14.014760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b300e44c76d'
down_revision = '8d0746779509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('assist',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=6),
               existing_nullable=False)
        batch_op.alter_column('pay',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=6),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('pay',
               existing_type=sa.String(length=6),
               type_=sa.VARCHAR(length=3),
               existing_nullable=True)
        batch_op.alter_column('assist',
               existing_type=sa.String(length=6),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)

    # ### end Alembic commands ###
