"""drop column

Revision ID: 8d0746779509
Revises: 1a4a8f3bdffe
Create Date: 2024-11-01 02:55:09.175152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d0746779509'
down_revision = '1a4a8f3bdffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('social_security')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('social_security', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
