"""add column

Revision ID: 95c8df9a7b9f
Revises: 87471b0ed727
Create Date: 2024-10-12 04:14:21.361082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c8df9a7b9f'
down_revision = '87471b0ed727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurrence_type', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('recurrence_interval', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('recurrence_interval')
        batch_op.drop_column('recurrence_type')

    # ### end Alembic commands ###
