"""add social security

Revision ID: a64a0e2e6852
Revises: f3545ce21ccc
Create Date: 2024-10-06 16:16:41.109805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a64a0e2e6852'
down_revision = 'f3545ce21ccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('social_security', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('social_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'socialsecurities', ['social_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('social_id')
        batch_op.drop_column('social_security')

    # ### end Alembic commands ###
