"""delete column

Revision ID: b3a31cafc702
Revises: 95c8df9a7b9f
Create Date: 2024-10-14 03:28:52.848585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3a31cafc702'
down_revision = '95c8df9a7b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint('appointments_session_id_fkey', type_='foreignkey')
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('appointments_session_id_fkey', 'sessions', ['session_id'], ['id'])

    # ### end Alembic commands ###
